### ISSUE TITLE
Installer failing to install

### ISSUE THREAD

**Issue by askdata01** [MeasureTheFuture/installer#5]
After two failed attempts, thought I'd ask for clarification.  I am not able to install the software.  The installer fails to install the required dependencies and when I run the commands outside the script, it looks as though none of the libav or libsw dependencies installed.  Also, hostapd is not being installed and without that, I doubt the wifi will function as a hotspot.
And it would help a lot if the script made a back up of the network configuration before overwriting it as that makes it most difficult to revert to a working network to try to fix.

**Comment by griffey** [comment]
The full installation instructions, including the necessary RTC module instructions, are at http://measurethefuture.net/build/. These are dev-facing instructions that should be updated to direct people to the main website. Sorry for issues, but if build according the the website, you should get a functional sensor.
